// <auto-generated />
using System;
using DesafioFull_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioFull_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210104020337_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("DesafioFull_WebAPI.Models.Divida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Devedor")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Juros")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Multa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Plano")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dividas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "12345612348",
                            Devedor = "Antonio",
                            Juros = 2m,
                            Multa = 3m,
                            Numero = 1234,
                            Plano = 2
                        });
                });

            modelBuilder.Entity("DesafioFull_WebAPI.Models.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("DividaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DividaId");

                    b.ToTable("Parcelas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataVencimento = new DateTime(2019, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DividaId = 1,
                            Numero = 1,
                            Valor = 95.5m
                        },
                        new
                        {
                            Id = 2,
                            DataVencimento = new DateTime(2019, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DividaId = 1,
                            Numero = 2,
                            Valor = 96m
                        });
                });

            modelBuilder.Entity("DesafioFull_WebAPI.Models.Parcela", b =>
                {
                    b.HasOne("DesafioFull_WebAPI.Models.Divida", "Divida")
                        .WithMany("Parcelas")
                        .HasForeignKey("DividaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
